greeting:
  - "&7Hello &f{{PLAYERNAME}}&7!"
  - "&7Welcome to the &l&dPLAY&aFRIENDS &r&7Minecraft Server!"
  - ""
  - "&7We only have two rules:"
  - "&7 1. &fNo griefing or stealing."
  - "&7 2. &fHave fun!"
  - ""

messages:
  first-join: "&l&d* &r&f{{PLAYERNAME}} &ejoined the server &bfor the first time&e!"
  nth-join: "&l&d* &r&f{{PLAYERNAME}} &ejoined the server."
  quit: "&l&d* &r&f{{PLAYERNAME}} &eleft the server."
  kick: "&l&d* &r&f{{PLAYERNAME}} &cwas kicked from the server."

peaceful:
  default: true
  greeting:
    enabled: "&7Chill mode is enabled. See &e/help chill."
    disabled: "&7Thrill mode is enabled. See &e/help thrill."
  messages:
    change-to-peaceful: "&7You are now in chill mode. Use the &e/thrill &7command if you want to fight monsters."
    already-peaceful: "&7You are already in chill mode. Use the &e/thrill &7command if you want to fight monsters."
    change-to-hostile: "&7You are now in thrill mode. Use the &e/chill &7command if you want monsters to leave you alone."
    already-hostile: "&7You are already in thrill mode. Use the &e/chill &7command if you want monsters to leave you alone."
    cant-attack-hostile: "&cYou cannot attack monsters because you are in chill mode. &7Use the &e/thrill &7command if you want to fight monsters."

sleepvoting:
  threshold:
    constant: 2
    percentage: 50
  messages:
    player-sleeping: "&f%s &eis now sleeping."
    x-out-of-y: "&eSleep voting: &f%d &ein bed, &f%d &erequired."
    success: "&eSleep voting: &fsuccess&e!"
    aborted-cant-sleep: "&eSleep voting: &caborted &ebecause sleeping is not possible anymore."
    aborted-nobody-sleeping: "&eSleep voting: &caborted &ebecause nobody is sleeping anymore."
    spawnpoint-set: "&bYour spawnpoint has been set to this bed."
    spawnpoint-hint: "&7Hold sneak and use the bed to set your spawn point."
    moved-worlds: "&eSleep voting: &f%s &eused a portal."

afk:
  timeout: 1
  messages:
    away: "&7AFK detection: You are inactive."
    back: "&7AFK detection: Welcome back!"