name: "PlayFriendsPlugin"
version: "0.7"
author: "Jochem Kuijpers"
main: "playfriends.mc.plugin.Main"
api-version: "1.19"
commands:
  chill:
    description: "Chill mode: monsters can't attack you, and you can't attack them. Opposite of /thrill."
    usage: "Usage: /chill"
  thrill:
    description: "Thrill mode: monsters can attack you, and you can attack them! Opposite of /chill."
    usage: "Usage: /thrill"
  zzz:
    description: "Vote for skipping the night without having to sleep in a bed."
    usage: "Usage: /zzz"