greeting:
  - "&7Hello &f{{PLAYERNAME}}&7!"
  - "&7Welcome to the &l&dPLAY&aFRIENDS &r&7Minecraft Server!"
  - ""
  - "&7We only have two rules:"
  - "&7 1. &fNo griefing or stealing."
  - "&7 2. &fHave fun!"
  - ""

messages:
  first-join: "&l&d* &r&f{{PLAYERNAME}} &ejoined the server &bfor the first time&e!"
  nth-join: "&l&d* &r&f{{PLAYERNAME}} &ejoined the server."
  quit: "&l&d* &r&f{{PLAYERNAME}} &eleft the server."
  kick: "&l&d* &r&f{{PLAYERNAME}} &cwas kicked from the server."

peaceful:
  default: true
  greeting:
    enabled: "&7Chill mode is enabled. See &e/help chill&7."
    disabled: "&7Thrill mode is enabled. See &e/help thrill&7."
  messages:
    change-to-peaceful: "&7You are now in chill mode. Use the &e/thrill &7command if you want to fight monsters."
    already-peaceful: "&7You are already in chill mode. Use the &e/thrill &7command if you want to fight monsters."
    change-to-hostile: "&7You are now in thrill mode. Use the &e/chill &7command if you want monsters to leave you alone."
    already-hostile: "&7You are already in thrill mode. Use the &e/chill &7command if you want monsters to leave you alone."
    cant-attack-hostile: "&cYou cannot attack monsters because you are in chill mode. &7Use the &e/thrill &7command if you want to fight monsters."

perf:
  window-in-seconds: 10

sleepvoting:
  threshold:
    constant: 2
    percentage: 50
  messages:
    player-sleeping: "&f%s &eis now sleeping."
    x-out-of-y: "&eSleep voting: &f%d &ein bed, &f%d &erequired."
    success: "&eSleep voting: &fsuccess&e!"
    aborted-cant-sleep: "&eSleep voting: &caborted &ebecause sleeping is not possible anymore."
    aborted-nobody-sleeping: "&eSleep voting: &caborted &ebecause nobody is sleeping anymore."
    moved-worlds: "&eSleep voting: &f%s &eused a portal."
    vote-by-command: "&eSleep voting: &f%s &evoted to sleep with &f/zzz."
    vote-by-command-not-allowed: "&cAt least one person must sleep in a bed to start sleep voting."

afk:
  timeout-seconds: 60
  greeting:
    enabled: "&7AFK detection is enabled. See &e/help afktoggle&7."
    disabled: "&7AFK detection is disabled. See &e/help afktoggle&7."
  messages:
    away: "&7AFK detection: You are inactive."
    back: "&7AFK detection: Welcome back!"
    enabled: "&7AFK detection is now enabled."
    disabled: "&7AFK detection is now disabled."

keepinventory:
  messages:
    items-and-xp-restored: "&7Your kept (some of) your items and your XP due to &e/keepinventory&7 and &e/keepxp&7."
    items-restored: "&7Your kept (some of) your items due to &e/keepinventory&7."
    xp-restored: "&7Your kept your XP due to &e/keepxp&7."
    set-none: "&7Keepinventory: &eNo items &7will be kept when you die."
    set-armor: "&7Keepinventory: &eOnly armor &7will be kept when you die."
    set-enchanted: "&7Keepinventory: &eOnly enchanted items &7will be kept when you die."
    set-all: "&7Keepinventory: &eAll items &7will be kept when you die."
    set-xp-disabled: "&7Keepxp: Your XP &ewill not be kept &7when you die."
    set-xp-enabled: "&7Keepxp: Your XP &ewill be kept &7when you die."

playerprofile:
  nameplate: "&dPronouns: &f{{PRONOUNS}}\n&aDiscord: &f{{DISCORD}}"
  greeting:
    no-pronouns:  "&7You have not set any pronouns. See &e/help pronouns"
    pronouns:  "&7Your pronouns are set as &f{{PRONOUNS}}. &7See &e/help pronouns"
    no-discord:  "&7You have not set a discord name. See &e/help discord"
    discord:  "&7Your discord name is set to &f{{DISCORD}}&7. See &e/help discord"
  chat:
    message: "<{{PLAYER}}> {{MESSAGE}}"
  commandfeedback:
    pronouns-set: "&7Your pronouns have been set to &f{{PRONOUNS}}"
    discord-set: "&7Your discord username has been set to &f{{DISCORD}}"
  list:
    message: "&7Players online: &f{{PLAYERS}}"
    separator: "&7, &f"
